### ISSUE TITLE
Absolute value for initial width

### ISSUE THREAD

**Issue by calvincramer** [waqasilyas/userscripts#2]
In order to use on a vertical monitor (leet hacker!) I had to change the initial 650px to a percentage:

https://github.com/waqasilyas/userscripts/blob/eb309b50a02f7f886f56e92befe468ead2191c9d/edstem/edstem_compact_view.js#L92

Changing 650px to 40% looks ok for me.

Thanks for making edstem decent to use!

**Comment by waqasilyas** [comment]
30% looked ok on landscape so i made a compromise and set it to 35% :)

Thanks for the issue.
